name: leafcutter_longread
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base>=4.3
  - r-data.table
  - r-tidyverse
  - r-magrittr
  - bioconductor-rtracklayer
  - r-matrix
  - r-igraph
  - r-optparse
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - pip:
    - rpy2>=3.5.0
    - torch>=2.0.0
    - pyro-ppl>=1.8.0
    - tqdm
