# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "gzip"
description: Compress files using gzip
keywords:
  - gzip
  - compression
tools:
  - "gzip":
      description: "gzip is a file compression tool"
      homepage: "https://www.gnu.org/software/gzip/"
      documentation: "https://www.gnu.org/software/gzip/manual/"

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - archive:
        type: file
        description: File to be compressed
        pattern: "*"

output:
  - gzip:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.gz":
          type: file
          description: Compressed file
          pattern: "*.gz"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@JTL-lab"
maintainers:
  - "@JTL-lab"
